import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Counter from '../store/Counter'
import { useSelector } from 'react-redux'

import {
  selectCount,
} from '../store/counterSlice'


export default function Home() {
  const count = useSelector(selectCount)

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.test}>
        <h1 className="">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p>{count}</p>
        <p className="">
          Get started by editing{' '}
          <code className="">pages/index.js</code>
        </p>

        <Counter />


    </main>

      <footer className="bg-yellow-300">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className="test">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
